# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-17 05:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mdgen', '0002_country_countrydata'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=128)),
                ('data', models.TextField()),
            ],
        ),
    ]
